# Generated by Django 5.1.4 on 2025-01-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Complete'), ('O', 'Overdue')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
